package com.usa.web.pages;

import io.qameta.allure.Step;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.ui.Select;


public class LandingPage extends BasePage {

    @FindBy(css = "input[id^=aria-autogenerated]")
    private WebElement loanAmount;

    @FindBy(css = "select[aria-label ='Loan Purpose']")
    private WebElement loanPurposeDropdown;

    @FindBy(css = "button[type=submit]")
    private WebElement checkYourRateButton;

    public LandingPage(WebDriver driver) {
        super(driver);
        refresh();
    }

    public void open(String url) {
        LOG.info("Open with url: " + url);
        driver.get(url);
    }

    @Step("Enter loan amount and loan purpose, then click Check Your Rate button")
    public void goToLoanPurposePage(int amount, String loanPurpose) {
        LOG.info("Navigate to Loan purpose page");
        helper.enterText(loanAmount, String.valueOf(amount));
        selectLoanPurpose(loanPurpose);
        helper.clickOnElement(checkYourRateButton);
    }

    private void selectLoanPurpose(String option) {
        Select select = new Select(loanPurposeDropdown);
        select.selectByVisibleText(option);
    }
}
